#!/usr/bin/env php
<?php
require_once __DIR__.'/vendor/autoload.php';
use Crada\Apidoc\Builder;
use Crada\Apidoc\Exception;
$classes = array(
    // Controllers
);
$output_dir  = __DIR__.'/public/apidocs';
$output_file = 'api.html'; // defaults to index.html
try {
    $builder = new Builder($classes, $output_dir, 'Jiuchun User API(V1.0.0)', $output_file);
    $builder->generate();
} catch (Exception $e) {
    echo 'There was an error generating the documentation: ', $e->getMessage();
}
